ZPTXDev/Quaver

- main.js
Context:
https://discord.com/channels/906471497231630336/920107978760261663/950441345703637003
https://discord.com/channels/906471497231630336/920107978760261663/950458256030068787
Instead of exiting the process immediately, using shuttingDown would make the sending of `MUSIC_RESTART` when there's queues during exits consistent, at the same time the process will exit with success code 0 as well.
Prior to this, `MUSIC_RESTART` doesn't get sent to the player queue text channel consistently whenever `exit` is executed from the terminal.
> refactor: use shuttingDown when exiting

- main.js
Whenever SIGTERM is called, it uses the MUSIC_RESTART_CRASH locale, this resolves it, and will instead use MUSIC_RESTART.
> refactor: include SIGTERM check for MUSIC_RESTART

- main.js
Addresses permission issues on `interactionCreate`
With this
- Quaver will send the missing permissions of **the text channel it is trying to send to** in an ephemeral to the user.
`VIEW_CHANNEL` - Can't view the channel but can see messages, should prevent unwanted crashes etc.
`SEND_MESSAGES` - Can view the channel but can't send any messages.
If both checks fail, will push both checks to the user.
Fixes #130 completely.
Adds a failsafe for #128
Tried to make it take the least amount of lines possible, I still feel like this can be improved with the same functionality.
While waiting for that new slash command feature, I think this one is ok for now.
> fix: permission check on text channel (fixes #130)

- main.js
- settings.example.json
Closes #131
I chose reconnect delay as `5000` because this doesn't happen much often, but please suggest better value for this.
I chose reconnect tries as `5` times only as an example, I am waiting for suggestions for the default values for all of these.
For infinite amount of tries, use `-1`
> feat: lavalink reconnect options

- main.js
I let lavaclient's error listener to shutDown Quaver instead because it can produce errors for logging.
> feat: shut down on caught lavalink error instead

- commands/bind.js
A check is missing arguments for a locale variable when sending its replyData.
> fix: missing args

- events/music/error.js
- main.js
Fixes #171 
I changed and passed a custom eventType name of `Lavalink Error` instead for to specify that it is a Lavalink error and unrelated to Quaver.
I added `Lavalink Error` eventType in one of the first filters for it to not treat the event as a crash.
I did not add `Lavalink Error` in one of the last filters of the function because it is an error in general anyway, so I let it log the error in error.log.
If there is a better name for the said eventType. Please, suggest.
Also, please check for any more oversights.
> fix: filter lavalink error

- main.js
Adds a check so it will not try to push `null`, addresses the issue that makes Quaver not exit the process fully when shuttingDown on some conditions.
Particularly this https://github.com/ZapSquared/Quaver/issues/167#issuecomment-1087831820
> fix: add a check to not push a null "current"

- locales/fil-PH.json
Adds missing strings for fil-PH locale.
> feat(locales): update fil-PH locale

- events/voiceStateUpdate.js
Fixes #183
This was supposed to come with #151
I added this check for Quaver to leave the stage channel if it lacks permissions to view the channel, connect, or speak in the stage channel.
As we all know, try catch catches the error "Missing Permissions" prior to this, this prevents it from happening again.
> fix: check for permissions for stage channel

- events/voiceStateUpdate.js
Fixes #182
This was supposed to come with #151
I added this check for Quaver to leave the voice channel if it lacks permissions to view the channel, connect, or speak in the voice channel.
As we all know, try catch catches the error "Missing Permissions" prior to this, this prevents it from happening again.
> fix: check for permissions for voice channel

- events/interactionCreate.js
`checks` should be `check(s)` as indication that the check may be a plural or a singular.
This is for to be consistent with
https://github.com/ZapSquared/Quaver/blob/db20a8c57e98e1ba309ad4612fa8cce143f92de7/main.js#L26
> refactor: rename checks to use parenthetical plurals

- events/interactionCreate.js
Fixes #191
For me I see two or more ways of implementing this
1.
```js
if (interaction.guildId) {
if (!interaction.channel.permissionsFor(interaction.client.user.id).has(perm)) {
failedPermissions.bot.push(perm);
}
}
```
2.
```js
if (interaction.guildId && !interaction.channel.permissionsFor(interaction.client.user.id).has(perm)) {
failedPermissions.bot.push(perm);
}
```
3.
```js
if (!interaction.guildId) return;
if (!interaction.channel.permissionsFor(interaction.client.user.id).has(perm)) {
failedPermissions.bot.push(perm);
}
```
I chose the first one because it is much more readable than it already was with the 2nd one, 3rd …
> fix: check for guild on interactions (Fixes #191)

- events/music/connect.js
Fixes #187
Creates a new MusicHandler object for player when reconnecting to a voice channel from the 24/7 feature.
#187 is related to this because there is no MusicHandler for player, Quaver cannot disconnect from the voice channel on shuttingDown because it is trying to call an Object that does not exist.
Similar problem arises when trying to play any track with Quaver when it reconnects from 24/7.
> fix: create new MusicHandler for player on reconnect (Fixes #187)

- events/voiceStateUpdate.js
Adds a check at the end of voice and stage channel checks for Quaver to update the 24/7 channel when it is moved.
> fix: update 247 channel when moved (Fixes #188)

- commands/loop.js
- commands/queue.js
- commands/remove.js
- events/interactionCreate.js
Reverts some unnecessary changes made from https://github.com/ZapSquared/Quaver/commit/6bde4a11c613cf984a9c1fae2260a893aa38ce7e#
Why they're reverted? Which files?
1. `loop.js` should not have any changes.
2. `queue.js`'s command name should not have any changes.
3. `remove.js` integer option name should not have any changes.
4. `interactionCreate.js`'s switch case names should not have any changes.
> fix: revert unnecessary assignments (Fixes #207)

- functions.js
Fixes #211
Removes unnecessary `.json` on require statement.
Because this prevents Quaver from locating its locale strings.
> fix: locate en-US strings at the right directory (Fixes #211)

- classes/MusicHandler.js
- commands/disconnect.js
- commands/play.js
- events/interactionCreate.js
- events/music/queueFinish.js
- events/music/trackEnd.js
- events/voiceStateUpdate.js
- main.js
Fixes #126
Ends the stage when Quaver gets disconnected from a Stage Channel that has a Stage Instance active.
This is not a full implementation since I excluded one condition. 
- `voiceChannel` is for fetching the cache of the guild and channels for the active player and direct interactions only.
e.g. User uses the `/disconnect` command, disconnects Quaver and ends the stage instance if one was present.
- `oldState` channel, should only handle ending stage on disconnections for `voiceStateUpdate` only. (**UPDATE**: Superseded by the first way of implementation.)
e.g. User manually disconnects Quaver, counts as a …
> fix: end stage on disconnection if it exists (Fixes #126)

- commands/play.js
Fixes #198
I did this because `state.channel.type` is returning always `null` for some reason
> refactor: check the right channel (Fixes #198)

- classes/MusicHandler.js
Fixes #223
Adds an optional chaining operator before checking channels, return as undefined.
For Quaver to not crash when it leaves a guild from the guildDelete event.
> fix: add necessary optional chaining operator (Fixes #223)

- events/voiceStateUpdate.js
Fixes #225
Adds an optional chaining operator before oldState channel type, return as undefined.
For Quaver to not crash when it leaves a guild from the guildDelete event.
> fix: add necessary optional chaining operator (Fixes #225)

- events/interactionCreate.js
This reimplements search to use a similar approach on `/play`, since play is using MusicHandler.locale, I thought search would be able to use that feature as well.
> refactor: reimplement search to use ReplyHandler.locale

- events/interactionCreate.js
Fixes #227
Instead of joining the channel while search is queuing up tracks, this change will make Quaver only join the voice/stage channel once the tracks are loaded, with that, we don't need to implement anymore checks for when it gets disconnected while queuing.
> fix: only join channel once tracks are loaded with search (Fixes #227)

- classes/MusicHandler.js
Closes #237
Bound is the correct past tense of bind.
> refactor: use correct past tense of bind

- classes/MusicHandler.js
- commands/play.js
- events/interactionCreate.js
- events/music/connect.js
Adds a `client` parameter to MusicHandler constructor and using it instead, for to minimize imports of `bot`.
> refactor: add client parameter for MusicHandler

- events/interactionCreate.js
Fixes #250
`Try/catch` would be useless without using `await`
> fix: use await on interaction update

- locales/en/cmd.json
- locales/en/discord.json
`permissions` should be `permission(s)` as indication that the `permission` may be a plural or a singular.
> refactor: rename permissions to use parenthetical plurals

- classes/PlayerHandler.js
- main.js
Closes #236
When shuttingDown, will use PlayerHandler's send method instead.
> refactor: use PlayerHandler#send on shuttingDown()

- main.js
An extension of pull request #307 that fully resolves issue #306
Addresses remaining invokers of `shuttingDown()` not using await.
> refactor: use await for remaining shuttingDown() invokers

- commands/play.js
On loadTypes `NO_MATCHES` and `LOAD_FAILED` should return to not proceed the queueing process any further. This affects functionality otherwise.
Fixes #320.
> fix: use return instead of break

- events/voiceStateUpdate.js
Fixes #174
Removes a statement preventing Quaver from setting pause timeout when a user immediately leaves from a voice or stage channel after queueing a track.
> fix: trigger pause timeout when there are no humans

- events/voiceStateUpdate.js
When moved to a stage channel with no humans, Quaver should set pause timeout when there is a track playing. Otherwise, disconnect from being alone.
Fixes #343
**Testing**
> What I did in the video
1. Start Quaver
2. User joins a voice channel
3. User plays any track
4. User moves Quaver to a stage channel
5. User moves to the stage channel as well to resume session
6. User skips the current playing track
7. User moves Quaver to a voice channel for it to leave due to being alone while nothing is playing.
> After that, I did the shorter alternative
1. User moves to a voice channel
2. User plays any track in the voice channel
3. User …
> fix(voiceStateUpdate): set pause timeout when moved to stage

- events/guildDelete.js
- events/music/queueFinish.js
- events/music/trackEnd.js
- events/voiceStateUpdate.js
Closes #347
Only adds await to PlayerHandler method invokers that needs it. Invokers that were in `setTimeout` function were excluded from the change.
> refactor: add missing await to PlayerHandler method invokes

- events/voiceStateUpdate.js
Affects functionality
Fixes #350
Should not clear and set a new pauseTimeout if it already exists.
When setting a new pauseTimeout, clear any pauseTimeout at any cost even if it can be `undefined` at `/** Checks for when a user leaves */`
> fix: do not set a "new pause timeout" if it exists

- commands/playing.js
Closes #366
Update deprecated code from usage of a deprecated property from lavaclient dependency.
> refactor: use lavaclient's Player#position instead

- classes/PlayerHandler.js
Fixes #371
Prevents `TypeErrors` caused by Kicking or Banning Quaver out of guilds.
Adds optional chaining operators for the checks to return false when attempting to check undefined text channels.
> fix(PlayerHandler#send): catch undefined text channels

- classes/PlayerHandler.js
- events/guildDelete.js
Fixes #373
Let `voiceStateUpdate` do the job alone instead of invoking `PlayerHandler#disconnect()` again from `guildDelete` where it is no longer supposed to when the bot already left the guild.
> fix(guildDelete): remove redundant invocation of PlayerHander#disconnect

- commands/play.js
- components/selects/play.js
Instead of having `commands/play.js` or `components/selects/play.js` unsuppress Quaver and having to type check them, why not removing them and let `voiceStateUpdate` do the job alone of unsuppressing Quaver.
> fix: let voiceStateUpdate unsuppress instead

- components/selects/play.js
For consistency. In other files, the locale gets sent before `PlayerHandler#disconnect` is invoked.
> refactor(select-play): send the locale before invoking PlayerHandler#disconnect

- commands/play.js
- components/selects/play.js
Fixes #385
Adds a check for when Quaver gets timed out while it is queueing tracks.
Updated the documentation accordingly.
Adds optional chaining operators for when `members` becomes `null` 
It is in one line together with the `// that kid left while we were busy` condition.
> fix: destroy the player if timed out while queuing tracks

- events/music/connect.js
Closes #395
Adds a failsafe for when reconnecting to a voice channel while the bot is not inside that guild.
> refactor: add failsafe to prevent reconnecting if guild is missing

- classes/PlayerHandler.js
Fixes #391
A timed out user or bot will not be able to end stage instances.
There should be a check here, conditioning that if timed out, do not attempt to delete it, otherwise a DiscordApiError: Missing permissions would occur.
> fix(PlayerHandler#disconnect): do not end stage if timed out

- commands/play.js
- components/selects/play.js
Fixes #392
Destroy the player if kicked or banned while queuing tracks, sends the locales only if there is a guild.
> fix: check for guild before queuing tracks

- commands/queue.js
Moves a constant below an if statement. No need to paginate when there are no tracks. Makes it return earlier when there are no tracks.
> refactor(command-queue): paginate only when there are tracks

- main.js
Affects functionality.
Closes #416
On `shuttingDown()` invocation, Quaver should no longer get stuck whatever happens inside `shuttingDown()`
In the `try` clause is where Quaver does what it should do when shutting down, cleaning up.
In the `catch` clause, we only log the error(s) that occurs in the `try` clause.
In the `finally` clause, we should `destroy()` the bot and `process.exit()` no matter what the outcome is.
> refactor: use try-catch-finally in shuttingDown()

- scripts/delete-commands.js
- scripts/deploy-commands.js
#434
Updates REST and discord-api-types used to v10 for the following scripts:
`deploy-commands.js`
`delete-commands.js`
> chore(scripts): update REST and discord-api-types used to v10

- src/commands/search.js
Closes #442
Makes use of `ReplyHandler#reply`. Reduces `commands/search.js`'s imports.
> refactor(command-search): use ReplyHandler#reply

- locales/en/cmd.js
- src/commands/play.js
Closes #444
If the host provided blank spotify credentials in their Quaver instance and a discord user queries a spotify link, sends a locale, informing the discord user that the feature is disabled. While at the same time refraining from resolving the spotify query. 
Otherwise, `interactionCreate` will handle the error if the host provided invalid credentials instead.
> feat(command-play): disable feature if spotify credentials are blank

- src/commands/247.js
Fixes #456
Emits the queueFinish event for the purpose of setting time out when 24/7 is disabled while nothing is playing.
> fix(command-247): set timeout on 24/7 disable while nothing playing

- locales/en/cmd.js
- locales/en/misc.js
- src/commands/queue.js
- src/components/modals/queue.js
- src/events/interactionCreate.js
Updates queue to use a modal to go to pages, and adds the relevant portion to interactionCreate event to handle modals.
> feat: use modal for queue pages

- locales/en/misc.js
- src/commands/search.js
- src/components/buttons/cancel.js
- src/components/buttons/search.js
- src/components/selectmenus/search.js
Adds an Add button to the search command, allowing the user to add tracks between pages.
> feat: persist search across pages

- CONFIGURATION.md
- settings.example.json
- src/lib/util/settings.ts
- src/main.ts
We have discussed this before that we keep it the way it is, but I still think a boolean would make this better.
Should be toggleable with a boolean instead of removing the properties to toggle it off.
> refactor: use a boolean for web.https

- locales/en/cmd.js
- locales/en/music.js
`[**x**](y)` makes more sense than `**[x](y)**`.
> refactor(locales): markdown inconsistency

- src/commands/queue.ts
- src/commands/search.ts
- src/components/buttons/format.ts
- src/components/buttons/queue.ts
- src/components/buttons/search.ts
- src/components/modals/queue.ts
- src/events/interactionCreate.ts
- src/lib/util/util.ts
uses colons as the delimiter for custom IDs instead of the common underscore to prevent conflicts (this is a parity PR with Warden)
> refactor: use colon for custom IDs

- locales/en/cmd.js
- src/commands/play.ts
- src/components/selectmenus/source.ts
- src/events/web/update.ts
- src/lib/util/common.d.ts
- src/lib/util/constants.ts
- src/lib/util/util.ts
- src/main.ts
Adds configurable default source to allow for changing from ytmsearch to something else. (useful for recent ratelimit issues)
> feat: configurable default source

- src/events/voiceStateUpdate.ts
Context: https://discord.com/channels/906471497231630336/920107978760261663/1355600350249488566
I'm looking for feedback on this refactor and any suggestions for improvement. Let me know if any changes are needed to better align with the codebase.
Some verbose comments were removed and comments were rewritten like this: `<reasoning statement>, <action statement>`
This pull request carefully refactors the listener for `Client#voiceStateUpdate` and aims to reduce code complexity, flattens out the flow of statements so they're less hard to traverse and read. Applies minor optimizations and simplifies some checks. So uh, basically …
> refactor(voiceStateUpdate): reduce nesting and flatten for clarity

- src/events/voiceStateUpdate.ts
Because neither TypeScript nor ESLint warned about this.
Also adjusts the callers' arguments since the parameter wasn't used anymore (from a prior pr)
> refactor(voiceStateUpdate): remove unused parameter
