commands/play.js, main.js
=> fix: crash when view_channel denied

commands/play.js, main.js
Fixes #109
For both the play command and search command.
=> fix: send interaction cancellation message to channel instead

main.js
=> fix: no readline SIGINT event listener

main.js
Rename to `inProgress` to make it more obvious, easier to read and understand than it already is.
=> refactor: rename variable inprg to inProgress

locales/ceb-PH.json
Adds missing strings for ceb-PH locale.
=> feat(locales): update ceb-PH locale

events/voiceStateUpdate.js
After reading thoroughly.
A return statement is missing here.
Can cause other issues if not addressed.
=> fix: missing return statement

classes/MusicHandler.js
Fixes #206
I am not sure to be honest, but these changes fixes it, for now...
There should be a better way.
Still trying to find a reasonable statement why.
=> fix: reimplement an import (Fixes #206)

main.js
Making it more obvious than it already is.
=> refactor: rename line to input

settings.example.json, shared.js
=> refactor: rename database to database_uri

main.js
=> refactor: rename voiceData to payload

events/music/error.js, main.js
Closes #306
There are no underlying issues after 4.0.0-next.1's release, so it was marked as a feature instead.
=> feat: add await to callers of shuttingDown()

shared.js
The former seems over-engineered. This one is an alternative.
=> refactor: use nullish coalescing operator instead of an assignment

commands/play.js, locales/en/cmd.json
handles NO_MATCHES and LOAD_FAILED
=> fix: handle other LoadTypes

commands/247.js
fixes incorrect locale key usage ("FUNCTION_DISABLED" -> "FEATURE_DISABLED")
=> fix: incorrect locale key

events/music/queueFinish.js, events/voiceStateUpdate.js
=> fix: rare pause timeout bug

events/voiceStateUpdate.js
Closes #341
Change the method used from find() to get() for code quality.
=> refactor(voiceStateUpdate): use get() method instead of find()

events/voiceStateUpdate.js
This statement was added from attempts on fixing #155 but other than that, it technically didn't contribute into fixing it and was left here for a long time.
The commit of this statement's origin: https://github.com/ZPTXDev/Quaver/commit/4539265c784efd7433c8279fd32e03faeb0e19b9
[3.4.0-next.19](https://github.com/ZPTXDev/Quaver/releases/tag/3.4.0-next.19)
=> refactor(voiceStateUpdate): remove redundant statement

events/voiceStateUpdate.js
Aims to bring more clarity and explicitness to `voiceStateUpdate` documentation. If there is something that doesn't look good, please suggest changes as necessary.
=> docs(voiceStateUpdate): update documentation

components/selects/playSelect.js, events/interactionCreate.js, main.js
Closes #333
Implementation of a select menu handler through the use of Collection()
=> refactor: select menu handler using Collection()

events/voiceStateUpdate.js
Reverts https://github.com/ZPTXDev/Quaver/blob/e764d77ed3030f58df2dbb84e5dcb4fe8a1f92a7/main.js#L641
Closes #380
The bug fix attempt didn't actually fix the #155 bug prior, so this pull request reverts that change.
=> refactor(voiceStateUpdate): revert previously ineffective fix

commands/skip.js
Fixes #378
I hope I used the right check
=> fix: do not skip if nothing is playing

commands/search.js
Editing a deferred reply with the ephemeral property does not turn the said message into an ephemeral, so using this property is not needed.
=> refactor(command-search): remove ephemeral property

commands/resume.js
Fixes #418
Affects functionality
=> fix(command-resume): start queue when resumed while paused

lib/PlayerHandler.js, src/commands/pause.js, src/commands/resume.js, src/events/music/trackStart.js, src/events/voiceStateUpdate.js, src/main.js
=> refactor: misc enhancements

src/events/error.js
Fixes #440
I overlooked this because this change was from the time Quaver was in CommonJS. I transitioned it to ESM, the pull request got merged from updating the branch upstream without testing, unaware this can cause a circular import.
=> fix(event-error): circular import

src/main.js
This was here because the PR that contained these changes were merged first before the PR that introduced the `no-return-await` rule.
Removes redundant `await` usages, will stay async. Fixes ESLint's errors.
=> refactor: remove redundant await

lib/util/common.js
=> fix(util-common): use correct property

lib/PlayerHandler.js, lib/ReplyHandler.js, lib/util/util.js, src/commands/247.js, src/commands/bassboost.js, src/commands/loop.js, src/commands/nightcore.js, src/commands/ping.js, src/commands/play.js, src/commands/playing.js, src/commands/queue.js, src/commands/search.js, src/commands/skip.js, src/commands/volume.js, src/components/buttons/cancel.js, src/components/buttons/queue.js, src/components/selectmenus/play.js, src/events/music/queueFinish.js, src/events/music/trackStart.js, src/events/voiceStateUpdate.js
Simplify getLocale calls by adding a asynchronous getGuildLocale function
=> feat: simplify guild locales

src/main.js
=> refactor: use getGuildLocale() instead of getLocale()

locales/en/cmd.js, locales/en/misc.js, src/commands/clear.js, src/commands/disconnect.js, src/commands/stop.js, src/components/buttons/cancel.js, src/components/buttons/clear.js, src/components/buttons/disconnect.js, src/components/buttons/stop.js
Adds a confirmation dialog for commands that might clear the queue.
=> feat: confirmation dialog for clear related commands

src/main.js
=> refactor(shuttingDown): check if err is an Error object

src/commands/clear.js, src/commands/disconnect.js, src/commands/search.js, src/commands/settings.js, src/commands/stop.js, src/components/buttons/format.js, src/components/buttons/search.js, src/components/selectmenus/language.js, src/components/selectmenus/search.js, src/components/selectmenus/settings.js
Fixes #499
Hotfix, affects functionality, the issue can cause a crash.
=> fix: catch errors when state time outs edit deleted messages

src/lib/PlayerHandler.ts, src/lib/ReplyHandler.ts
=> refactor: optimize locale method

src/events/music/trackStart.ts
Should show the dashboard button if the web feature is enabled as well.
=> refactor: show dashboard button if web is enabled

src/main.ts
To keep up with discord.js' API updates.
Ensure usages of Client#login() and Client#destroy() are properly awaited to prevent race conditions and unexpected behavior during connection setup and cleanup.
=> fix(main#discordClient): await login and destroy

src/events/voiceStateUpdate.ts
Unsuppress Quaver after stage instance creation instead.
Fixes #1325
Regression
=> fix(voiceStateUpdate): ensure Quaver is unsuppressed after stage instance creation (Fixes #1325)

CONFIGURATION.md, locales/en/music.js, settings.example.json, src/events/music/trackStart.ts, src/lib/util/settings.d.ts, src/lib/util/util.ts
Adds configurable source emojis.
=> feat: source emojis
